informalsystems/sovereign-ibc

Cargo.lock, Cargo.toml, mocks/Cargo.toml, mocks/src/sovereign/handle.rs, modules/sov-ibc-transfer/Cargo.toml, modules/sov-ibc-transfer/src/lib.rs, modules/sov-ibc/Cargo.toml, modules/sov-ibc/src/clients/context.rs, modules/sov-ibc/src/context.rs, modules/sov-ibc/src/lib.rs, modules/sov-ibc/src/query/methods.rs
=> deps: bump ibc to v0.46 and tendermint to v0.34

modules/sov-ibc/src/clients/context.rs, modules/sov-ibc/src/context.rs, modules/sov-ibc/src/lib.rs, modules/sov-ibc/src/query/context.rs
=> chore: implement `QueryContext` methods 

mocks/src/cosmos/app.rs, mocks/src/lib.rs, mocks/src/relayer/context.rs, mocks/src/relayer/handle/cosmos.rs, mocks/src/relayer/handle/mod.rs, mocks/src/relayer/handle/rollup.rs, mocks/src/relayer/mod.rs, mocks/src/relayer/relay.rs, mocks/src/setup.rs, mocks/src/sovereign/rollup.rs, mocks/src/tests/client.rs, modules/sov-ibc/src/context.rs, modules/sov-ibc/src/lib.rs
=> test: create dummy rollup client on Cosmos chain

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, mocks/Cargo.toml, mocks/src/configs.rs, mocks/src/cosmos/app.rs, mocks/src/cosmos/builder.rs, mocks/src/lib.rs, mocks/src/relayer/context.rs, mocks/src/relayer/handle/cosmos.rs, mocks/src/relayer/handle/mod.rs, mocks/src/relayer/handle/rollup.rs, mocks/src/relayer/mod.rs, mocks/src/relayer/relay.rs, mocks/src/setup.rs, mocks/src/sovereign/celestia.rs, mocks/src/sovereign/config.rs, mocks/src/sovereign/da_service.rs, mocks/src/sovereign/mod.rs, mocks/src/sovereign/rollup.rs, mocks/src/tests/client.rs, mocks/src/tests/transfer.rs, mocks/src/utils.rs
=> feat: refactor mock rollup to work with generic DA 

.github/workflows/rust.yml, Cargo.lock, Cargo.toml, mocks/Cargo.toml, mocks/src/configs.rs, mocks/src/relayer/builder.rs, mocks/src/sovereign/rollup.rs, mocks/src/sovereign/runner.rs, mocks/src/sovereign/runtime/config.rs, mocks/src/sovereign/runtime/mod.rs, mocks/src/tests/client.rs, modules/sov-ibc/src/call.rs, modules/sov-ibc/src/context.rs, modules/sov-ibc/src/lib.rs, modules/sov-ibc/src/query/methods.rs
Two of the tests failed because of the issue described in #66.
=> deps: update Sovereign SDK dependencies

clients/sov-celestia-cw/src/entrypoints.rs, clients/sov-celestia-cw/src/handlers.rs, clients/sov-celestia-cw/src/types/error.rs, clients/sov-celestia-cw/src/types/msgs.rs, clients/sov-celestia-cw/src/types/response.rs, clients/sov-celestia/types/src/client_message/misbehaviour.rs, clients/sov-celestia/types/src/client_message/mod.rs
=> imp: update `execute` and `query` handlers to align with ibc-go v7.3

.github/workflows/cw-check.yml, .github/workflows/risc0-check.yml, .github/workflows/rust.yml, Makefile
Closes: #83
- Few minor workflow improvements along with this PR
______
=> imp: add CI job for checking WASM file build

Cargo.lock, Cargo.toml, clients/sov-celestia/src/client_state.rs, clients/sov-celestia/src/consensus_state.rs, clients/sov-celestia/types/src/client_message/aggregated_proof.rs, clients/sov-celestia/types/src/client_message/header.rs, clients/sov-celestia/types/src/client_message/mod.rs, clients/sov-celestia/types/src/client_state/da_params.rs, clients/sov-celestia/types/src/client_state/definition.rs, clients/sov-celestia/types/src/client_state/mod.rs, clients/sov-celestia/types/src/consensus_state/da_params.rs, clients/sov-celestia/types/src/consensus_state/definition.rs, clients/sov-celestia/types/src/consensus_state/mod.rs, mocks/Cargo.toml, mocks/src/sovereign/rollup.rs, proto/buf.lock, proto/ibc/lightclients/sovereign/tendermint/v1/sov_tendermint.proto, proto/sovereign/types/v1/types.proto
Closes: #85
In addition to the `PublicInput` updates, this PR enhances the clarity of both the `ClientState` and `ConesensusState` definitions by converting the field associated with DA parameters into a generic `Da` type.
______
=> refactor: update `PublicInput` and `ConsensusState` definitions

docs/RelayerWorkflow.md
[📖 Rendered](https://github.com/informalsystems/sovereign-ibc/blob/d04a4fa91cbc58b69b39ab5d9b0a38bc05eb2b29/docs/RelayerWorkflow.md)
Part of #32
=> docs: navigate through relayer workflow and PRC calls

modules/sov-ibc/src/context.rs
=> imp: use `ModuleInfo::prefix(&self)` for implementing `commitment_prefix`

Cargo.lock, clients/sov-celestia-cw/Cargo.toml, clients/sov-celestia-cw/src/context/client_ctx.rs, clients/sov-celestia-cw/src/context/core_ctx.rs, clients/sov-celestia-cw/src/context/mod.rs, clients/sov-celestia-cw/src/entrypoints.rs, clients/sov-celestia-cw/src/handlers.rs, clients/sov-celestia-cw/src/lib.rs, clients/sov-celestia-cw/src/tests.rs, clients/sov-celestia-cw/src/types/consensus_state.rs, clients/sov-celestia-cw/src/types/msgs.rs, clients/sov-celestia/types/src/client_message/header.rs, clients/sov-celestia/types/src/client_message/misbehaviour.rs, clients/sov-celestia/types/src/client_message/mod.rs, clients/sov-celestia/types/src/client_state/definition.rs, clients/sov-celestia/types/src/client_state/mod.rs, clients/sov-celestia/types/src/consensus_state/definition.rs, mocks/Cargo.toml
Closes: #65
CC @ljoss17
______
=> imp: make CosmWasm create and update client functional

Cargo.lock, Cargo.toml, mocks/Cargo.toml, mocks/src/configs.rs, mocks/src/relayer/builder.rs, mocks/src/relayer/handle/rollup.rs, mocks/src/relayer/mod.rs, mocks/src/relayer/msgs/rollup.rs, mocks/src/sovereign/manual.rs, mocks/src/sovereign/rollup.rs, mocks/src/sovereign/runner.rs, mocks/src/sovereign/runtime/config.rs, mocks/src/sovereign/runtime/mod.rs, mocks/src/tests/transfer.rs, modules/sov-ibc-transfer/src/context.rs, modules/sov-ibc-transfer/src/genesis.rs, modules/sov-ibc-transfer/src/lib.rs, modules/sov-ibc-transfer/src/rpc.rs, modules/sov-ibc-transfer/src/utils.rs, modules/sov-ibc/src/call.rs, modules/sov-ibc/src/clients/context.rs, modules/sov-ibc/src/clients/mod.rs, modules/sov-ibc/src/context.rs, modules/sov-ibc/src/genesis.rs, modules/sov-ibc/src/lib.rs, modules/sov-ibc/src/router.rs, modules/sov-ibc/src/rpc/context.rs, modules/sov-ibc/src/rpc/methods.rs
Closes: #6
Along with this PR, Sovereign SDK dependencies have been updated to rev: `5a144d60`
______
=> imp: cache escrow address + update Sovereign SDK dependencies

mocks/src/sovereign/rollup.rs, mocks/src/sovereign/runner.rs, mocks/src/sovereign/runtime/mod.rs
=> fix(sov-ibc-mocks): update `visible_slot_number` by resolving context

Cargo.lock, Cargo.toml, clients/sov-celestia/types/Cargo.toml, clients/sov-celestia/types/src/client_message/aggregated_proof.rs, clients/sov-celestia/types/src/client_message/header.rs, clients/sov-celestia/types/src/client_message/mod.rs, clients/sov-celestia/types/src/client_message/pretty.rs, mocks/Cargo.toml, proto/ibc/lightclients/sovereign/tendermint/v1/sov_tendermint.proto, proto/sovereign/types/v1/types.proto
=> chore: update `AggregatedProofPublicInput` definition

Cargo.lock, Cargo.toml, clients/sov-celestia/types/src/client_state/mod.rs, mocks/Cargo.toml, mocks/src/cosmos/manual.rs, mocks/src/relayer/handle/rollup.rs, mocks/src/relayer/msgs/cosmos.rs, mocks/src/relayer/msgs/rollup.rs, mocks/src/sovereign/manual.rs, mocks/src/tests/transfer.rs, modules/sov-ibc/src/rpc/methods.rs
This PR updates `ibc` dependencies to revision `984f5cd`.
=> chore: update `ibc` revision to include request/response domain types from `ibc-query` 

Cargo.lock, Cargo.toml, clients/sov-celestia-cw/src/tests.rs, clients/sov-celestia/Cargo.toml, clients/sov-celestia/src/client_state/common.rs, clients/sov-celestia/types/Cargo.toml, clients/sov-celestia/types/src/client_message/aggregated_proof.rs, clients/sov-celestia/types/src/client_message/mod.rs, mocks/Cargo.toml, mocks/src/cosmos/app.rs, mocks/src/relayer/builder.rs, mocks/src/relayer/handle/cosmos.rs, mocks/src/relayer/handle/mod.rs, mocks/src/relayer/handle/rollup.rs, mocks/src/relayer/msgs/cosmos.rs, mocks/src/relayer/msgs/rollup.rs, mocks/src/sovereign/manual.rs, mocks/src/sovereign/rollup.rs, mocks/src/sovereign/runner.rs, mocks/src/tests/client.rs, mocks/src/tests/transfer.rs, modules/sov-ibc/src/rpc/helpers.rs, modules/sov-ibc/src/rpc/methods.rs, modules/sov-ibc/src/rpc/mod.rs
=> feat(sov-celestia-client): implement JMT commitment proof verification methods

Cargo.lock, Cargo.toml, clients/sov-celestia-cw/src/tests.rs, clients/sov-celestia/src/client_state/misbehaviour.rs, clients/sov-celestia/src/client_state/mod.rs, clients/sov-celestia/src/client_state/update_client.rs, clients/sov-celestia/src/client_state/validation.rs, clients/sov-celestia/types/src/client_message/aggregated_proof.rs, clients/sov-celestia/types/src/client_message/header.rs, clients/sov-celestia/types/src/client_message/misbehaviour.rs, clients/sov-celestia/types/src/client_message/mod.rs, clients/sov-celestia/types/src/client_state/definition.rs, clients/sov-celestia/types/src/client_state/mod.rs, mocks/Cargo.toml, mocks/src/cosmos/manual.rs, modules/sov-consensus-state-tracker/src/mock_da.rs
=> feat: implement `verify_client_message` method for DA (Celestia) part

Cargo.lock, clients/sov-celestia/src/client_state/update_client.rs, clients/sov-celestia/src/client_state/validation.rs, clients/sov-celestia/types/src/consensus_state/definition.rs, mocks/Cargo.toml
=> feat: implement `check_misbehaviour` method for DA(Celestia) part

Cargo.lock, Cargo.toml, clients/sov-celestia-cw/src/context/client_ctx.rs, clients/sov-celestia-cw/src/context/mod.rs, clients/sov-celestia-cw/src/handlers.rs, clients/sov-celestia-cw/src/tests.rs, clients/sov-celestia-cw/src/tests/fixture.rs, clients/sov-celestia-cw/src/tests/mod.rs, clients/sov-celestia-cw/src/types/client_type.rs, clients/sov-celestia-cw/src/types/msgs.rs, clients/sov-celestia-cw/src/types/utils.rs, clients/sov-celestia/src/client_state/execution.rs, clients/sov-celestia/src/client_state/mod.rs, clients/sov-celestia/src/client_state/update_client.rs, clients/sov-celestia/src/client_state/validation.rs, clients/sov-celestia/src/consensus_state.rs, clients/sov-celestia/types/src/client_state/definition.rs, clients/sov-celestia/types/src/client_state/mod.rs, mocks/Cargo.toml, modules/sov-ibc/src/clients/mod.rs
=> feat: implement client recovery

modules/sov-ibc-transfer/src/context.rs
Along with this PR, a few methods were added to reduce code duplications.  
______
=> fix: trace prefix check in escrow/unescrow when TokenId is IBC-created

docs/architecture/adr-001-transfer-module-implementation.md
[📖 Rendered](https://github.com/informalsystems/sovereign-ibc/blob/farhad/adr-001-transfer-module-impl/docs/architecture/adr-001-transfer-module-implementation.md)
=> docs: ADR-001 Transfer Module Implementation

clients/sov-types/src/aggregated_proof.rs
=> imp: add upper bound to length of public data fields

.cargo/config.toml, Cargo.lock, clients/sov-celestia/src/client_state/execution.rs, clients/sov-celestia/src/client_state/validation.rs, nix/sov-celestia-cw.nix
=> feat: implement `prune_oldest_consensus_state`

docs/architecture/adr-002-light-client-implementation.md
[📖 Rendered](https://github.com/informalsystems/sovereign-ibc/blob/farhad/adr02-light-client-impl/docs/architecture/adr-002-light-client-implementation.md)
Closes: #149
______
=> docs: ADR-002 Sovereign IBC light client implementation

.cargo/config.toml, Cargo.lock, Cargo.toml, clients/sov-celestia/cw-contract/src/client_type.rs, clients/sov-celestia/src/client_state/execution.rs, clients/sov-celestia/src/client_state/misbehaviour.rs, clients/sov-celestia/src/client_state/update_client.rs, clients/sov-celestia/src/client_state/validation.rs, clients/sov-celestia/src/consensus_state.rs, mocks/src/cosmos/app.rs, mocks/src/cosmos/configs.rs, modules/sov-ibc/src/clients/mod.rs, nix/sov-celestia-cw.nix
Closes: #XXX
contains the changes for `ibc-rs` v0.53.0
basecoin PR: informalsystems/basecoin-rs#184
---
=> update to `ibc-rs` v0.53.0

.cargo/config.toml, Cargo.lock, Cargo.toml, flake.lock, nix/sov-celestia-cw.nix
Closes: #159
- ibc-rs now unpacks host client state from counterparty according to the client id at counterparty: cosmos/ibc-rs#1246
---
=> Update ibc-proto and ibc-rs

.cargo/config.toml, Cargo.lock, clients/sov-celestia/cw-contract/Cargo.toml, clients/sov-celestia/cw-contract/src/entrypoint.rs, clients/sov-celestia/cw-contract/src/tests/fixture.rs, flake.lock, nix/sov-celestia-cw.nix
Closes: #XXX
- Includes cosmos/ibc-rs#1252
- Follows [rano/downgrade-borsh](https://github.com/cosmos/ibc-rs/tree/rano/downgrade-borsh) branch of `ibc-rs`
---
=> update `ibc-rs` and `cosmwasm` deps

modules/sov-consensus-state-tracker/src/celestia_da.rs, modules/sov-consensus-state-tracker/src/lib.rs
=> fix: build correct host ConsensusState
